import { test, expect } from '@playwright/test'

test('actual office model renders and camera controls work', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  const glbResponse = page.waitForResponse(response => response.url().endsWith('/models/office-plan.glb'))
  await page.goto('/')
  await page.getByLabel('Render quality').selectOption('balanced')
  expect((await glbResponse).status()).toBe(200)
  const viewer = page.locator('.viewport')
  await expect(viewer).toHaveAttribute('data-ready', 'true')
  await expect(page.getByText('Original model loaded')).toBeVisible()
  await expect(page.getByText('1.38M')).toBeVisible()
  await page.waitForTimeout(1000)
  const initial = Number(await viewer.getAttribute('data-camera-distance'))
  await page.getByRole('button', { name: 'Zoom in', exact: true }).click()
  await expect.poll(async () => Number(await viewer.getAttribute('data-camera-distance'))).toBeLessThan(initial * .85)
  await page.getByRole('button', { name: 'Zoom out', exact: true }).click()
  await expect.poll(async () => Number(await viewer.getAttribute('data-camera-distance'))).toBeGreaterThan(initial * .95)
  const before = await viewer.getAttribute('data-camera-position')
  await page.getByRole('button', { name: 'Auto rotate', exact: true }).click()
  await expect.poll(() => viewer.getAttribute('data-camera-position')).not.toBe(before)
  await expect(page.getByRole('button', { name: 'Auto rotate', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Auto rotate', exact: true }).click()
  await page.getByRole('button', { name: 'Top view', exact: true }).click()
  await expect.poll(async () => { const xyz = (await viewer.getAttribute('data-camera-position')).split(',').map(Number); return xyz[1] > Math.abs(xyz[0]) * 100 }).toBe(true)
  await page.waitForTimeout(700)
  const topCanvas = await page.locator('canvas').boundingBox()
  const topDistance = Number(await viewer.getAttribute('data-camera-distance'))
  const beforeCursorZoom = (await viewer.getAttribute('data-camera-position')).split(',').map(Number)
  await page.mouse.move(topCanvas.x + topCanvas.width * .66, topCanvas.y + topCanvas.height * .45)
  await page.mouse.wheel(0, -250)
  await expect.poll(async () => Number(await viewer.getAttribute('data-camera-distance'))).toBeLessThan(topDistance)
  // Off-center zoom must move toward the cursor, not just along the center axis.
  await expect.poll(async () => Number((await viewer.getAttribute('data-camera-position')).split(',')[0])).toBeGreaterThan(beforeCursorZoom[0] + .2)
  await page.getByRole('button', { name: 'Reset view', exact: true }).click()
  await expect.poll(async () => Math.abs(Number((await viewer.getAttribute('data-camera-position')).split(',')[0]))).toBeLessThan(.05)
  await page.getByRole('button', { name: 'Perspective', exact: true }).click()
  await page.waitForTimeout(1000)
  const canvas = page.locator('canvas')
  const box = await canvas.boundingBox()
  const cx = box.x + box.width / 2, cy = box.y + box.height / 2
  const orbitBefore = await viewer.getAttribute('data-camera-position')
  await page.mouse.move(cx, cy); await page.mouse.down(); await page.mouse.move(cx + 90, cy + 45, { steps: 10 }); await page.mouse.up()
  await expect.poll(() => viewer.getAttribute('data-camera-position')).not.toBe(orbitBefore)
  const panBefore = await viewer.getAttribute('data-camera-position')
  await page.mouse.move(cx, cy); await page.mouse.down({ button: 'right' }); await page.mouse.move(cx + 50, cy, { steps: 8 }); await page.mouse.up({ button: 'right' })
  await expect.poll(() => viewer.getAttribute('data-camera-position')).not.toBe(panBefore)
  const wheelBefore = Number(await viewer.getAttribute('data-camera-distance'))
  await page.mouse.wheel(0, -250)
  await expect.poll(async () => Number(await viewer.getAttribute('data-camera-distance'))).toBeLessThan(wheelBefore)
  await page.getByRole('button', { name: 'Reset view', exact: true }).click()
  await expect.poll(async () => Math.abs(Number(await viewer.getAttribute('data-camera-distance')) - initial)).toBeLessThan(.5)
  await page.getByRole('button', { name: 'Fullscreen', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Exit fullscreen', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Exit fullscreen', exact: true }).click()
  await page.getByRole('button', { name: 'Front camera view', exact: true }).click()
  await expect.poll(async () => Math.abs(Number((await viewer.getAttribute('data-camera-position')).split(',')[0]))).toBeLessThan(.05)
  await page.getByRole('button', { name: 'Side camera view', exact: true }).click()
  await expect.poll(async () => Math.abs(Number((await viewer.getAttribute('data-camera-position')).split(',')[2]))).toBeLessThan(.05)
  const widthBefore = (await viewer.boundingBox()).width
  await page.getByRole('button', { name: 'Expand workspace', exact: true }).click()
  await expect.poll(async () => (await viewer.boundingBox()).width).toBeGreaterThan(widthBefore + 200)
  await expect(page.locator('.inspector')).toBeHidden()
  await page.getByRole('button', { name: 'Show model settings', exact: true }).click()
  await page.getByRole('button', { name: '3D camera view', exact: true }).click()
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Save PNG screenshot', exact: true }).click()
  const download = await downloadEvent
  expect(download.suggestedFilename()).toBe('office-view.png')
  await download.saveAs('test-results/exported-view.png')
  await page.getByLabel('Brightness', { exact: false }).press('End')
  await expect(page.getByLabel('Brightness', { exact: false })).toHaveValue('1.5')
  await page.getByRole('button', { name: 'Restore lighting' }).click()
  await expect(page.getByLabel('Brightness', { exact: false })).toHaveValue('0.9')
  await page.getByLabel('Render quality').selectOption('high')
  await expect(page.getByText('High quality', { exact: true })).toBeVisible()
  await page.waitForTimeout(1500)
  await page.locator('.inspector').evaluate(element => { element.scrollTop = 0 })
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true })
  expect(errors).toEqual([])
})

test('mobile layout stays within screen and original scene loads', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 })
  const page = await context.newPage()
  await page.goto('/')
  await expect(page.locator('.viewport')).toHaveAttribute('data-ready', 'true')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Help & shortcuts' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: 'Close help' }).click()
  const viewer = page.locator('.viewport')
  const box = await page.locator('canvas').boundingBox()
  const cx = box.x + box.width / 2, cy = box.y + box.height / 2
  const cdp = await context.newCDPSession(page)
  const beforeOrbit = await viewer.getAttribute('data-camera-position')
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: cx, y: cy, id: 1 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: cx + 65, y: cy + 20, id: 1 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect.poll(() => viewer.getAttribute('data-camera-position')).not.toBe(beforeOrbit)
  const beforePinch = Number(await viewer.getAttribute('data-camera-distance'))
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: cx - 25, y: cy, id: 1 }, { x: cx + 25, y: cy, id: 2 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: cx - 70, y: cy, id: 1 }, { x: cx + 70, y: cy, id: 2 }] })
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect.poll(async () => Number(await viewer.getAttribute('data-camera-distance'))).toBeLessThan(beforePinch)
  await page.getByRole('button', { name: 'Reset view', exact: true }).click()
  await page.waitForTimeout(1500)
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true })
  await context.close()
})

test('failed model request shows an actionable error', async ({ page }) => {
  await page.route('**/models/office-plan.glb', route => route.abort())
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'We couldn’t open the scene' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Retry viewer' })).toBeVisible()
  await page.unroute('**/models/office-plan.glb')
  await page.getByRole('button', { name: 'Retry viewer' }).click()
  await expect(page.locator('.viewport')).toHaveAttribute('data-ready', 'true')
})
